### ISSUE TITLE
卸载某些应用会导致系统崩溃重启

### ISSUE THREAD

**Issue by aohanhongzhi** [aohanhongzhi/device_xiaomi_onclite#1]
1. 快图浏览
2. 哔站

**Comment by aohanhongzhi** [comment]
KeyChain shouldn't be removed! 移除了这个可能会导致系统重启。

**Comment by aohanhongzhi** [comment]
```
05-11 13:41:21.742  1489  1756 E WifiScoringParams: Invalid frequency(-1), using 5G as default rssi array
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: Exception when retrieving package:hxy.grandfather.live
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: android.content.pm.PackageManager$NameNotFoundException: hxy.grandfather.live
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:242)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:214)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.settings.applications.appinfo.AppButtonsPreferenceController.retrieveAppEntry(AppButtonsPreferenceController.java:372)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.settings.applications.appinfo.AppButtonsPreferenceController.refreshUi(AppButtonsPreferenceController.java:660)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.settings.applications.appinfo.AppButtonsPreferenceController.refreshAndFinishIfPossible(AppButtonsPreferenceController.java:508)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.settings.applications.appinfo.AppButtonsPreferenceController.handleActivityResult(AppButtonsPreferenceController.java:300)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.settings.applications.appinfo.AppInfoDashboardFragment.onActivityResult(AppInfoDashboardFragment.java:438)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:3011)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:2991)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:362)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:322)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:634)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.settings.SettingsActivity.onActivityResult(SettingsActivity.java:476)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.Activity.dispatchActivityResult(Activity.java:8385)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.os.Looper.loopOnce(Looper.java:201)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.os.Looper.loop(Looper.java:288)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at android.app.ActivityThread.main(ActivityThread.java:7871)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-11 13:41:22.798  5063  5063 E AppButtonsPrefCtl: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-11 13:41:23.148  3964  4082 E android.vendin: Failed to open APK '/data/app/~~r5cGkZBtzImyQMwAnHJ0-A==/hxy.grandfather.live-u9WpG1twHBKMtGQx-NXJvQ==/base.apk': I/O error
05-11 13:41:23.155  3964  4082 E android.vendin: Failed to open APK '/data/app/~~r5cGkZBtzImyQMwAnHJ0-A==/hxy.grandfather.live-u9WpG1twHBKMtGQx-NXJvQ==/base.apk': I/O error
05-11 13:41:23.157  3964  4082 E ResourcesManager: failed to add asset path '/data/app/~~r5cGkZBtzImyQMwAnHJ0-A==/hxy.grandfather.live-u9WpG1twHBKMtGQx-NXJvQ==/base.apk'
05-11 13:41:23.157  3964  4082 E ResourcesManager: java.io.IOException: Failed to load asset path /data/app/~~r5cGkZBtzImyQMwAnHJ0-A==/hxy.grandfather.live-u9WpG1twHBKMtGQx-NXJvQ==/base.apk
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:530)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:612)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:664)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager.createResources(ResourcesManager.java:1011)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1114)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2415)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1815)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1801)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1570)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3093)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:3072)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:273)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at android.app.ApplicationPackageManager.getApplicationIcon(ApplicationPackageManager.java:1634)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at ffq.a(PG:5)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at ffw.l(PG:1)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at fss.a(PG:57)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at fez.k(PG:3)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at feq.f(PG:3)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at feq.i(PG:3)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at ffu.i(Unknown Source:0)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at ffx.d(Unknown Source:10)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at ffx.e(PG:3)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at feh.apply(PG:192)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at afyx.e(PG:2)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at afyy.run(PG:9)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at gpy.run(PG:12)
05-11 13:41:23.157  3964  4082 E ResourcesManager: 	at java.lang.Thread.run(Thread.java:1013)
05-11 13:41:23.208  2320  2320 E PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
05-11 13:41:23.248  3964  3964 E Finsky  : [1] sum.b(9): STU: Failed to get status for package 'hxy.grandfather.live' (1601: Error getting stats)
05-11 13:41:23.248  3964  3964 E Finsky  : android.content.pm.PackageManager$NameNotFoundException: hxy.grandfather.live
05-11 13:41:23.248  3964  3964 E Finsky  : 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Parcel.readParcelable(Parcel.java:3333)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Parcel.createException(Parcel.java:2409)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Parcel.readException(Parcel.java:2392)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Parcel.readException(Parcel.java:2334)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.app.usage.IStorageStatsManager$Stub$Proxy.queryStatsForPackage(IStorageStatsManager.java:577)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.app.usage.StorageStatsManager.queryStatsForPackage(StorageStatsManager.java:213)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at pgc.run(PG:15)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Handler.handleCallback(Handler.java:938)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Looper.loopOnce(Looper.java:201)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Looper.loop(Looper.java:288)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.HandlerThread.run(HandlerThread.java:67)
05-11 13:41:23.248  3964  3964 E Finsky  : Caused by: android.os.RemoteException: Remote stack trace:
05-11 13:41:23.248  3964  3964 E Finsky  : 	at com.android.server.usage.StorageStatsService.queryStatsForPackage(StorageStatsService.java:300)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.app.usage.IStorageStatsManager$Stub.onTransact(IStorageStatsManager.java:261)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Binder.execTransactInternal(Binder.java:1179)
05-11 13:41:23.248  3964  3964 E Finsky  : 	at android.os.Binder.execTransact(Binder.java:1143)
05-11 13:41:23.248  3964  3964 E Finsky  : 
05-11 13:41:23.803  1913  1913 E BcSmartspaceCard: No tap action can be set up
05-11 13:41:23.806  2405  2405 E BcSmartspaceCard: No tap action can be set up
05-11 13:41:23.832  1489  1634 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.bg
05-11 13:41:23.832  1489  1634 E AndroidRuntime: java.lang.AssertionError: could not resolve KeyChainService
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.security.KeyChain.bindAsUser(KeyChain.java:1108)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.security.KeyChain.bindAsUser(KeyChain.java:1013)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.security.KeyChain.bind(KeyChain.java:999)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at com.android.server.devicepolicy.DevicePolicyManagerService$Injector.keyChainBind(DevicePolicyManagerService.java:1700)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at com.android.server.devicepolicy.DevicePolicyManagerService.lambda$removeCredentialManagementApp$0$DevicePolicyManagerService(DevicePolicyManagerService.java:1161)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at com.android.server.devicepolicy.DevicePolicyManagerService$$ExternalSyntheticLambda127.run(Unknown Source:4)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
05-11 13:41:24.509  3027  3027 E AndroidRuntime: FATAL EXCEPTION: main
05-11 13:41:24.509  3027  3027 E AndroidRuntime: Process: com.google.android.gms, PID: 3027
05-11 13:41:24.509  3027  3027 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:24.567  5346  6450 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
05-11 13:41:24.567  5346  6450 E AndroidRuntime: Process: bin.mt.plus, PID: 5346
05-11 13:41:24.567  5346  6450 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: FATAL EXCEPTION: main
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: Process: com.google.android.gms, PID: 3027
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: java.lang.RuntimeException: android.os.DeadSystemException
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at android.app.ContextImpl.unbindService(ContextImpl.java:2041)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:846)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at whq.h(:com.google.android.gms@221514044@22.15.14 (190400-441847897):4)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at whq.b(:com.google.android.gms@221514044@22.15.14 (190400-441847897):2)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at vws.handleMessage(:com.google.android.gms@221514044@22.15.14 (190400-441847897):9)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at alym.kj(:com.google.android.gms@221514044@22.15.14 (190400-441847897):0)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at alym.dispatchMessage(:com.google.android.gms@221514044@22.15.14 (190400-441847897):11)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at android.os.Looper.loopOnce(Looper.java:201)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at android.os.Looper.loop(Looper.java:288)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7871)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	Suppressed: ccfr: 
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 		at tk_trace.measurement-ChimeraMeasurementApiService-IMeasurementService_0_handler(Unknown Source:0)
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: Caused by: android.os.DeadSystemException
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 	... 14 more
05-11 13:41:24.608  3027  3027 E DeviceDoctorHandler: 
05-11 13:41:24.612  3027  3027 E BaseUncaughtHandler: Hit an exception while processing the UncaughtExceptionHandler. Original exception: 
05-11 13:41:24.612  3027  3027 E BaseUncaughtHandler: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:24.893   863  9439 E IPCThreadState: attemptIncStrongHandle(134): Not supported
05-11 13:41:24.893   863  9439 E IPCThreadState: attemptIncStrongHandle(136): Not supported
05-11 13:41:24.894   863  9439 E IPCThreadState: attemptIncStrongHandle(135): Not supported
05-11 13:41:24.894   863  9439 E IPCThreadState: attemptIncStrongHandle(137): Not supported
05-11 13:41:24.894   605   605 E LocSvc_GnssInterface: serviceDied] service died. cookie: 0, who: 0x712440d8a0
05-11 13:41:24.894   863  2110 E IPCThreadState: attemptIncStrongHandle(132): Not supported
05-11 13:41:24.901   518   518 E Zygote  : Zygote failed to write to system_server FD: Connection refused
05-11 13:41:24.901   518   518 E Zygote  : Exit zygote because system server (pid 1489) has terminated
05-11 13:41:24.936  2320  2320 E AndroidRuntime: FATAL EXCEPTION: main
05-11 13:41:24.936  2320  2320 E AndroidRuntime: Process: com.android.phone, PID: 2320
05-11 13:41:24.936  2320  2320 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:24.937  2582  3519 E AndroidRuntime: FATAL EXCEPTION: highpool[5]
05-11 13:41:24.937  2582  3519 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 2582
05-11 13:41:24.937  2582  3519 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: FATAL EXCEPTION: highpool[5]
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: Process: com.google.android.gms.persistent, PID: 2582
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: java.lang.RuntimeException: android.os.DeadSystemException
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1883)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at android.app.ContextImpl.startService(ContextImpl.java:1825)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at vmd.b(:com.google.android.gms@221514044@22.15.14 (190400-441847897):8)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at vmd.a(:com.google.android.gms@221514044@22.15.14 (190400-441847897):12)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at vmc.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):0)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at wll.c(:com.google.android.gms@221514044@22.15.14 (190400-441847897):6)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at wll.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):7)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at wqp.run(:com.google.android.gms@221514044@22.15.14 (190400-441847897):0)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	at java.lang.Thread.run(Thread.java:1013)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	Suppressed: ccfr: 
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 		at tk_trace.location_base-NetworkLocationChimeraService_onBind(Unknown Source:0)
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: Caused by: android.os.DeadSystemException
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 	... 11 more
05-11 13:41:24.946  2582  3519 E DeviceDoctorHandler: 
05-11 13:41:24.947  2582  3230 E AndroidRuntime: FATAL EXCEPTION: lowpool[3]
05-11 13:41:24.947  2582  3230 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 2582
05-11 13:41:24.947  2582  3230 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:24.963  1826  1826 E wpa_supplicant: Client died. Terminating...
=05-11 13:41:24.978   605   605 E LocSvc_GnssBatchingInterface: serviceDied] service died. cookie: 0, who: 0x712440dae0
05-11 13:41:24.978   605   605 E LocSvc_APIClientBase: locAPIStopSession:495] session -1 is not exist.
05-11 13:41:24.978   605   605 E LocSvc_APIClientBase: locAPIStopSession:495] session -1 is not exist.
05-11 13:41:24.987   605   605 E GnssHal_GnssGeofencing: serviceDied] service died. cookie: 0, who: 0x712440da60
05-11 13:41:25.005   517   577 E libnetd_resolv: unlinkToDeath: removed reference to death recipient but unlink failed.
05-11 13:41:25.005   517   580 E IPCThreadState: attemptIncStrongHandle(4): Not supported
05-11 13:41:25.015   517  9476 E resolv  : reportDnsEvent: DNS event not sent since no INetdEventListener receiver is available.
05-11 13:41:25.016   517  9478 E resolv  : reportDnsEvent: DNS event not sent since no INetdEventListener receiver is available.
05-11 13:41:25.020  2743  2743 E AndroidRuntime: FATAL EXCEPTION: main
05-11 13:41:25.020  2743  2743 E AndroidRuntime: Process: com.google.android.apps.wellbeing, PID: 2743
05-11 13:41:25.020  2743  2743 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:25.020  1881  1881 E AndroidRuntime: FATAL EXCEPTION: main
05-11 13:41:25.020  1881  1881 E AndroidRuntime: Process: com.google.android.dialer, PID: 1881
05-11 13:41:25.020  1881  1881 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:25.120  1881  1881 E DialerUncaughtExceptionHandlerProcessInitializer: com.google.android.libraries.processinit.finalizer.UncaughtExceptionHandlerProcessInitializer.lambda$init$0:53 Encountered uncaught exception.
05-11 13:41:25.120  1881  1881 E DialerUncaughtExceptionHandlerProcessInitializer: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:25.167  1881  4842 E AudioSystem-JNI: Command failed for android_media_AudioSystem_error_callback: -32
05-11 13:41:25.178  1881  1881 E DialerSilentCrashReporter: com.android.dialer.crashreporter.SilentCrashReporter.uncaughtException:112 sendSilentFeedback
05-11 13:41:25.178  1881  1881 E DialerSilentCrashReporter: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:25.193  1881  4824 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
05-11 13:41:25.193  1881  4824 E AndroidRuntime: Process: com.google.android.dialer, PID: 1881
05-11 13:41:25.193  1881  4824 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
05-11 13:41:25.203   850  1501 E QC-NETMGR-LIB: serviceDied(): Netd service died
05-11 13:41:25.268  1826  1826 E wpa_supplicant: Error deregistering for death notification for iface callback object
05-11 13:41:25.363   863  1805 E statsd  : Stats puller failed for tag: 10083 at 123848535264
05-11 13:41:25.363   863  1805 E statsd  : Stats puller failed for tag: 10104 at 123848535264
05-11 13:41:25.363   863  1805 E statsd  : Gauge Stats puller failed for tag: 10069 at 123848535264
05-11 13:41:25.363   863  1805 E statsd  : Gauge Stats puller failed for tag: 10042 at 123848535264
05-11 13:41:25.363   863  1805 E statsd  : Gauge Stats puller failed for tag: 10020 at 123848535264
05-11 13:41:25.363   863  1805 E statsd  : Gauge Stats puller failed for tag: 10045 at 123848535264
05-11 13:41:25.363   863  1805 E statsd  : Gauge Stats puller failed for tag: 10128 at 123848535264
05-11 13:41:25.363   863  9437 E IPCThreadState: attemptIncStrongHandle(4): Not supported
05-11 13:41:25.364   863  9437 E IPCThreadState: attemptIncStrongHandle(5): Not supported
05-11 13:41:25.364   863  9437 E IPCThreadState: attemptIncStrongHandle(6): Not supported
05-11 13:41:25.364   863  9437 E IPCThreadState: attemptIncStrongHandle(7): Not supported
05-11 13:41:25.364   863  9437 E IPCThreadState: attemptIncStrongHandle(8): Not supported
05-11 13:41:25.364   863  9437 E IPCThreadState: attemptIncStrongHandle(9): Not supported
05-11 13:41:25.364   863  9438 E IPCThreadState: attemptIncStrongHandle(94): Not supported
05-11 13:41:25.364   863  9437 E IPCThreadState: binder thread pool (9 threads) starved for 469 ms
05-11 13:41:25.364   863  2110 E IPCThreadState: attemptIncStrongHandle(3): Not supported
05-11 13:41:25.364   863  9437 E IPCThreadState: attemptIncStrongHandle(10): Not supported
05-11 13:41:25.364   863  9438 E IPCThreadState: attemptIncStrongHandle(11): Not supported

```

**Comment by aohanhongzhi** [comment]
每次卸载软件都会出现这个错误
```
05-11 13:41:23.832  1489  1634 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.bg
05-11 13:41:23.832  1489  1634 E AndroidRuntime: java.lang.AssertionError: could not resolve KeyChainService
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.security.KeyChain.bindAsUser(KeyChain.java:1108)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.security.KeyChain.bindAsUser(KeyChain.java:1013)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.security.KeyChain.bind(KeyChain.java:999)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at com.android.server.devicepolicy.DevicePolicyManagerService$Injector.keyChainBind(DevicePolicyManagerService.java:1700)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at com.android.server.devicepolicy.DevicePolicyManagerService.lambda$removeCredentialManagementApp$0$DevicePolicyManagerService(DevicePolicyManagerService.java:1161)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at com.android.server.devicepolicy.DevicePolicyManagerService$$ExternalSyntheticLambda127.run(Unknown Source:4)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-11 13:41:23.832  1489  1634 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```
所以问题应该和KeyChain相关，经过检查，作者去掉了这个软件，应该恢复即可。
